server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    username: root
    password: hjl20030110
mybatis-plus:
  config:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    config-location: classpath:/mybatis/mybatis-config.xml
